### ISSUE TITLE
Não funcionou comigo

### ISSUE THREAD

**Issue by wiranunes** [rafaelpatro/google-customer-reviews#5]
@rafaelpatro para mim aparece a seguinte mensagem na tela de confirmação do pedido

There has been an error processing your request
DateInterval::__construct(): Unknown or bad format (P2017-05-20D)

**Comment by rafaelpatro** [comment]
Como vc está preenchendo os campos nas configurações do módulo?

Em 19 de mai de 2017 12:25 PM, "wiranunes" <notifications@github.com>
escreveu:

**Comment by wiranunes** [comment]
@rafaelpatro coloquei de todas as formas inclusive a padrão Pattern: /([0-9]+) days/
Quebra a loja e fala que é invalid

**Comment by wiranunes** [comment]
Consegui manualmente mas essa string que precisa retornar o valor conforme as políticas do Google não encontrei ainda :(

**Comment by rafaelpatro** [comment]
Então, não sei se foi isso, mas o padrão de preenchimento do prazo precisa
ser condizente com seu método de entrega.
Ex.:
Título do frete: Correios - 10 dias úteis.
Padrão: / ([\d]+) dias/

Em 19 de mai de 2017 3:20 PM, "wiranunes" <notifications@github.com>
escreveu:

Consegui manualmente mas essa string que precisa retornar o valor conforme
as políticas do Google não encontrei ainda :(

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rafaelpatro/google-customer-reviews/issues/5#issuecomment-302775719>,
or mute the thread

**Comment by wiranunes** [comment]
@rafaelpatro veja como preenchi
![capturar](https://cloud.githubusercontent.com/assets/28536941/26323443/41c2df9e-3f05-11e7-9b62-363f18150bbd.PNG)

**Comment by rafaelpatro** [comment]
Está com a última atualização? Parece q está faltando um campo. Tente
atualizar para o branch master.

Em 22 de mai de 2017 3:42 PM, "wiranunes" <notifications@github.com>
escreveu:
